# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2b5198da86d598864921ac0775cab84a9798eb03f628c88fe287e229fd8437d65c0bce9bdcc0f5e36851fb21616b28bcb8cc2228c087558b96e1da8d7f95486

test:
  secret_key_base: 3ff9a26d9a57529a597fa702e3c96837507c065fc5209ca81d32d74af935909c23519baad1ddb6c683242042ed2e9e8594088908321ab4b3ed43d167ff710aad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
